[/Script/EngineSettings.GameMapsSettings]
EditorStartupMap=/Game/Map_CleverTapCppSample.Map_CleverTapCppSample
; GameDefaultMap=/Game/Map_CleverTapCppSample.Map_CleverTapCppSample
; ServerDefaultMap=/Game/Map_CleverTapCppSample.Map_CleverTapCppSample

[/Script/CleverTapSample.CppDemonstrationHUD]
CleverTapMainMenuViewClassName=/Game/UI/WBP_MainMenuView.WBP_MainMenuView_C
CleverTapLoginPageViewClassName=/Game/UI/WBP_LoginView.WBP_LoginView_C

[/Script/HardwareTargeting.HardwareTargetingSettings]
TargetedHardwareClass=Desktop
AppliedTargetedHardwareClass=Desktop
DefaultGraphicsPerformance=Maximum
AppliedDefaultGraphicsPerformance=Maximum

[/Script/Engine.Engine]
+ActiveGameNameRedirects=(OldGameName="TP_Blank",NewGameName="/Script/CleverTapSample")
+ActiveGameNameRedirects=(OldGameName="/Script/TP_Blank",NewGameName="/Script/CleverTapSample")

[/Script/AndroidRuntimeSettings.AndroidRuntimeSettings]
PackageName=com.clevertap.android.unreal.sample
StoreVersion=1
StoreVersionOffsetArmV7=0
StoreVersionOffsetArm64=0
StoreVersionOffsetX8664=0
ApplicationDisplayName=CleverTap Unreal Sample
VersionDisplayName=1.0
MinSDKVersion=21
TargetSDKVersion=33
InstallLocation=Auto
bEnableGradle=True
bEnableLint=False
bPackageDataInsideApk=True
bCreateAllPlatformsInstall=False
bDisableVerifyOBBOnStartUp=False
bForceSmallOBBFiles=False
bAllowLargeOBBFiles=False
bAllowPatchOBBFile=False
bAllowOverflowOBBFiles=False
bUseExternalFilesDir=True
bPublicLogFiles=True
Orientation=Sensor
MaxAspectRatio=2.100000
bUseDisplayCutout=False
bRestoreNotificationsOnReboot=False
bFullScreen=True
bEnableNewKeyboard=True
DepthBufferPreference=Default
bValidateTextureFormats=True
bEnableBundle=False
bEnableUniversalAPK=True
bBundleABISplit=True
bBundleLanguageSplit=True
bBundleDensitySplit=True
ExtraApplicationSettings=android:requestLegacyExternalStorage="true"
ExtraActivitySettings=
+ExtraPermissions=android.permission.MANAGE_EXTERNAL_STORAGE
bAndroidVoiceEnabled=False
bRemoveOSIG=False
+GoogleVRCaps=Daydream33
bGoogleVRSustainedPerformance=False
KeyStore=
KeyAlias=
KeyStorePassword=
KeyPassword=
bBuildForArmV7=True
bBuildForArm64=True
bBuildForX8664=False
bBuildForES31=True
bSupportsVulkan=False
bSupportsVulkanSM5=False
ClangSanitizer=None
bAndroidOpenGLSupportsBackbufferSampling=False
bDetectVulkanByDefault=True
bBuildWithHiddenSymbolVisibility=False
bSaveSymbols=False
bForceLDLinker=False
bEnableGooglePlaySupport=False
RequestCodeForPlayGamesActivities=80002
PlayGamesClientId=
bForceRefreshToken=False
GamesAppID=
bSupportAdMob=True
AdMobAppID=
TagForChildDirectedTreatment=TAG_FOR_CHILD_DIRECTED_TREATMENT_UNSPECIFIED
TagForUnderAgeOfConsent=TAG_FOR_UNDER_AGE_OF_CONSENT_UNSPECIFIED
MaxAdContentRating=MAX_AD_CONTENT_RATING_G
AdMobAdUnitID=
GooglePlayLicenseKey=
GCMClientSenderID=
bShowLaunchImage=True
bAllowIMU=False
bAllowControllers=True
bBlockAndroidKeysOnControllers=False
bControllersBlockDeviceFeedback=False
AndroidAudio=Default
AudioSampleRate=44100
AudioCallbackBufferFrameSize=1024
AudioNumBuffersToEnqueue=4
AudioMaxChannels=0
AudioNumSourceWorkers=0
SpatializationPlugin=
ReverbPlugin=
OcclusionPlugin=
CompressionOverrides=(bOverrideCompressionTimes=False,DurationThreshold=5.000000,MaxNumRandomBranches=0,SoundCueQualityIndex=0)
bUseAudioStreamCaching=False
CacheSizeKB=0
MaxChunkSizeOverrideKB=0
bResampleForDevice=False
SoundCueCookQualityIndex=-1
MaxSampleRate=0.000000
HighSampleRate=0.000000
MedSampleRate=0.000000
LowSampleRate=0.000000
MinSampleRate=0.000000
CompressionQualityModifier=0.000000
AutoStreamingThreshold=0.000000
AndroidGraphicsDebugger=None
MaliGraphicsDebuggerPath=(Path="")
bEnableMaliPerfCounters=False
bMultiTargetFormat_ETC2=True
bMultiTargetFormat_DXT=True
bMultiTargetFormat_ASTC=True
TextureFormatPriority_ETC2=0.200000
TextureFormatPriority_DXT=0.600000
TextureFormatPriority_ASTC=0.900000
SDKAPILevelOverride=
NDKAPILevelOverride=
bStreamLandscapeMeshLODs=False
bEnableDomStorage=False

[/Script/CleverTap.CleverTapConfig]
bAutoInitializeSharedInstance=True
ProjectId=YOUR_CLEVERTAP_PROJECT_ID
ProjectToken=YOUR_CLEVERTAP_TOKEN
RegionCode=
IdentityKeys=Identity,Email,Phone
EncryptionLevel=None
bUseCustomCleverTapId=False
bRequestInternetPermissions=True
bRequestGeoFencePermissions=False
DevelopmentLogLevel=Verbose
ShippingLogLevel=Verbose
bAndroidIntegrateFirebase=True
AndroidGoogleServicesJsonPath=Config/Android/google-services.json
AndroidSmallNotificationIconPath=Config/Android/Images/sample_small_notification_icon.png
AndroidImagesDir=Config/Android/Images
AndroidSoundsDir=Config/Android/Sounds
bAndroidEnablePullNotifications=True
AndroidNotificationChannelGroupSlot1=ID="general"
AndroidNotificationChannelGroupSlot2=ID="system"
AndroidNotificationChannelGroupSlot3=ID="marketing"
AndroidDefaultNotificationChannel=messages
AndroidNotificationChannelSlot1=ID="messages" | Group="general" | Importance=IMPORTANCE_HIGH | bShowBadge=True
AndroidNotificationChannelSlot2=ID="reminders" | Group="general" | Importance=IMPORTANCE_DEFAULT | bShowBadge=True | Sound="sfx_sounds_button1.wav"
AndroidNotificationChannelSlot3=ID="news" | Group="general" | Importance=IMPORTANCE_DEFAULT | bShowBadge=True | Sound="sfx_sounds_button2.wav"
AndroidNotificationChannelSlot4=ID="system_alerts" | Group="system" | Importance=IMPORTANCE_HIGH | bShowBadge=True
AndroidNotificationChannelSlot5=ID="updates" | Group="system" | Importance=IMPORTANCE_LOW | bShowBadge=False
AndroidNotificationChannelSlot6=ID="promotions" | Group="marketing" | Importance=IMPORTANCE_LOW | bShowBadge=True
AndroidNotificationChannelSlot7=ID="surveys" | Group="marketing" | Importance=IMPORTANCE_MIN | bShowBadge=False

; URL Handling
; ---------------------------
bIntegrateOpenUrl=True

; Example Slot1 - catches clevertap-unreal-sample://
DeepLinkSchemeFilterSlot1=clevertap-unreal-sample

; Example Slot2 - catches clevertap://unreal.com/sample
DeepLinkSchemeFilterSlot2=clevertap
DeepLinkHostFilterSlot2=unreal.com
DeepLinkPathPrefixFilterSlot2=/sample

; Example Slot3 - catches http://clevertap.com/unreal-sample,
; but requires digital verification that the app is approved for this domain
; See https://developer.android.com/training/app-links/verify-android-applinks
; DeepLinkSchemeFilterSlot3=http
; DeepLinkHostFilterSlot3=clevertap.com
; DeepLinkPathPrefixFilterSlot3=/unreal-sample
; AndroidIntentFilterSlot3_AutoVerify=True


[/Script/IOSRuntimeSettings.IOSRuntimeSettings]
bEnableRemoteNotificationsSupport=True
bSupportsPortraitOrientation=True
bSupportsUpsideDownOrientation=True

[/Script/AndroidFileServerEditor.AndroidFileServerRuntimeSettings]
bEnablePlugin=False
